### ISSUE TITLE
The file .gitignore is missing.

### ISSUE THREAD

**Issue by marcosdpeon** [CADViewer/cadviewer-conversion-server#3]
I think it's critical with that the file has been missed. Cloning the source code of this project is very slow.

**Comment by CADViewer** [comment]
Hello, @marcosdpeon , basically the repository contains several native code executables close to the GitHub 100Mb limit as well as there is a folder with a number of SHX fonts that ensures that CAD files from a number of different sources will convert, so the content of the repository reflects the files needed for the various functionality that the conversion server provides.
